spring:
  h2.console:
    enabled: true
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
rss:
  url: https://www.gazeta.ru/export/rss/first.xml
  reload:
    delay: 95000